config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins
  resources :reservations
  resources :reviews
  resources :uploads

  devise_for :users
  resources :users
  resources :users do
    resources :postings, :reviews
  end

  root "postings#splash"

  resources :categories do
    resources :postings
  end

  resources :postings do
    resources :reservations
    resources :reviews
  end

end

app/models/posting.rb
class Posting < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reservations
  has_many :reviews
  ratyrate_rateable "title"

  has_many :uploads

  self.per_page = 10

  after_save do
    GeocodeAddressJob.perform_later self
  end

  def address
    "#{street}, #{city}, #{state} #{zip}"
  end

  def geocode
    if street.present? && city.present? && state.present?
      RentMyThing.geocode address do |lon, lat|
        self.update_column :coords, [lon, lat]
        # save validate: false
      end
    end
  end

  def image?
    self.uploads.present?
  end

  def image
    if image?
      self.uploads.first
    else
      self.uploads.build
    end
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy ]
  before_action :load_categories, only: [:show, :edit, :new, :update ]
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :get_reviews, only: :show
  layout :resolve_layout

  def resolve_layout
    if action_name == "splash"
      "splash"
    else
      "application"
    end
  end

  def splash
  end

  # GET /postings
  # GET /postings.json
  def index
    @upload = Upload.new

    start_date = params[:start_date]
    end_date = params[:end_date]
    category_id = params[:category_id]
    search_string = params[:search_text]
    start_date = Date.strptime start_date, '%Y-%m-%d' if start_date.present?
    end_date = Date.strptime end_date, '%Y-%m-%d' if end_date.present?
    city = params[:city]

    #Hack to prevent will_paginate getting confused and giving me a nested route when I don't want one
    params.delete :category_id if params[:category_id].blank?
    @postings = Posting.order("updated_at DESC").paginate(:page => params[:page])


    if start_date.present? && end_date.present?
      @postings = @postings.where "available_dates && [?, ?)", start_date, end_date
    elsif start_date.present?
      @postings = @postings.where "?::date <@ available_dates", start_date
    elsif end_date.present?
      @postings = @postings.where "?::date <@ available_dates", end_date
    end

    if search_string.present?
      @postings = @postings.where "POSITION(:str in title) <> 0 OR POSITION(:str in description) <> 0", {str: search_string}
    end

    if category_id.present?
      @postings = @postings.where category_id: category_id
    end

    if city.present?
      @postings = @postings.where "lower(city) = lower(?)", city
    end

    # Map related.....
    # Build object to contain pin (map marker) type and coords (from @postings) to display on map
    # Before rendering the map first check to see if any of the postings have any coords..if not
    # map @mapAttributes-json object needed for map will not be built..note: corresponding javascript code
    # on webpage will check to see if @mapAttributes_json to see if object is nil..if nil it will not call
    # the function to build the map and hence no map will be rendered
    if (@postings.any?{|x| x.coords})
      @mapAttributes_json = RentMyThing.gather_map_attributes({"/images/red-pin.png" => @postings})
    end
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
    @review = Review.new
    @reviews = @posting.reviews

    # Map related.....
    # Build object to contain pin (map marker) type and coords (from @posting) to display on map
    # Before rendering the map first check to see if any of the postings have any coords..if not
    # map @mapAttributes_json object needed for map will not be built..note: corresponding javascript code
    # on webpage will check to see if @mapAttributes_json to see if object is nil..if nil it will not call
    # the function to build the map and hence no map will be rendered
    if @posting.coords
      @mapAttributes_json = RentMyThing.gather_map_attributes({"/images/red-pin.png" => @posting})
    end
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    # logger.debug "date range: #{params["rentrange"]["from"]} to #{params["rentrange"]["to"]} "
    @posting = Posting.new(posting_params)
    @posting.user = current_user

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        load_categories
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_reviews
      @reviews = Review.all
    end

    def load_categories
      @categories = Category.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :description, :category_id, :cost,
          :date_range, :street, :state, :zip, :phone, :email, :city, :image)
    end

end

app/helpers/postings_helper.rb
module PostingsHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def date_range_string_for_js date_range
    if date_range
      start = date_range.begin
      finish = date_range.end
      "{minDate: new Date(#{start.year}, #{start.mon}, #{start.day}), maxDate: new Date(#{finish.year}, #{finish.mon}, #{finish.day})}"
    else
      ""
    end
  end
end

app/views/postings/_carousel.html.erb
<div id="thumbnails" class="carousel slide" data-ride="carousel">
  <% if @posting.uploads.count > 0 %>
  <ol class="carousel-indicators">
    <% @posting.uploads.each_with_index do |image, i| %>
    <li data-target="#thumbnails" data-slide-to="<%= i %>" class="<%= i == 0 ? "active" : "" %>"></li>
    <% end %>
  </ol>
  <% end %>
  <div class="vehicle-make-model-and-name">
    <div class="carousel-inner">
      <% if @posting.uploads.count > 0 %>
        <% @posting.uploads.each_with_index do |image, i| %>
      <div class="item <%= i == 0 ? "active" : "" %>"><%= image_tag image.uploaded_file.url(:medium) %></div>
      <% end %>
      <% else %>
      <div class="item active">
        <img src="http://www.vinsmoselle.lu/media/cache/397_resized_700_700_90_516407cbbe17d_placeholder.jpg">
      </div>
      <% end %>
    </div>
  </div>
  <br>
  <a class="left carousel-control" href="#thumbnails" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#thumbnails" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h1 class="heading-text"><%= @posting.title %></h1>

app/views/postings/_category_picker.html.erb
<div class="field">
  <%= f.label :category_id, :class => "col-md-2" %><br>
  <%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name", @posting.category_id), { :include_blank => "Select category"}, { :class => "form-control styled-select col-md-10" } %>
</div>

app/views/postings/_form.html.erb
<%= form_for(@posting, :html => { :multipart => true }) do |f| %>
<% if @posting.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

  <ul>
    <% @posting.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td class="th-text col-md-2"><%= f.label :title, :class => "label-text" %></td>
      <td colspan="5" class="td-text col-md-10"><%= f.text_field :title, :class => "input-text" %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :description, :class => "label-text" %></td>
      <td colspan="5" class="td-text col-md-10"><%= f.text_area :description, { :class => "input-text textarea-styled", :style => "height: 120px; width: 600px" } %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :category_id, :class => "label-text" %></td>
      <td colspan="5" class="td-text col-md-10"><%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name", @posting.category_id), { :include_blank => "Select category"}, { :class => "input-text form-control styled-select col-md-10" } %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :cost, :class => "label-text" %></td>
      <td colspan="5" class="td-text col-md-10"><%= f.text_field :cost, :class => "input-text"  %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :street, :class => "label-text" %></td>
      <td colspan="5" class="td-text col-md-10"><%= f.text_field :street, :class => "input-text"  %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :city, :class => "label-text" %></td>
      <td class="td-text col-md-3"><%= f.text_field :city, :class => "input-text" %></td>
      <td class="th-text col-md-2"><%= f.label :state, :class => "label-text" %></td>
      <td class="td-text col-md-1"><%= f.select :state, options_for_select(us_states, @posting.state), { :include_blank => "Select state"}, { :class => "input-text styled-select col-md-1" }  %></td>
      <td class="th-text col-md-1"><%= f.label :zip, :class => "label-text" %></td>
      <td class="td-text col-md-1"><%= f.text_field :zip, :class => "input-text" %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :phone, :class => "label-text" %></td>
      <td colspan="5" class="col-md-10"><%= f.text_field :phone, :class => "input-text" %></td>
    </tr>
    <tr>
      <td class="th-text col-md-2"><%= f.label :email, :class => "label-text" %></td>
      <td colspan="5" class="td-text col-md-10"><%= f.text_field :email, :class => "input-text" %></td>
      <% end %>
    </tr>
    <tr>
      <td class="td-text" colspan="2"><%= render 'new_show' %></td>
    </tr>
  </tbody>
</table>

<div class="actions col-md-2">
  <%= submit_tag "Update Posting", :class => 'btn btn-primary', :role => "button" %>
  <br><br>
    <div class="btn-group">
    <%#= link_to 'Show', @posting, :class => "btn btn-primary", :role => "button" %>
    <%= link_to 'Back', postings_path, :class => "btn btn-primary", :role => "button" %>
  </div>
</div>

app/views/postings/_new_show.html.erb
<%= form_for @posting.uploads.build, :url => uploads_path, html: { multipart: true } do |f| %>
  <%= f.hidden_field :posting_id %>
  <%= f.label :uploaded_file, t('.upload_new_file') %>
  <%= f.file_field :uploaded_file, multiple: true, name: 'upload[uploaded_file]' %>
  <%= f.submit 'Save', class: 'btn' %>

  <% # jquery upload template # %>
  <script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>
  <div id="page" onclick="void(0)">
<% end %>

app/views/postings/_posting.html.erb
<%= posting.title %><br>

app/views/postings/_posting_table.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <td class="td-text col-md-12" id="description">
          <div class="th-text">About the rental:<br></div>
          <div class="td-text"><%= @posting.description %></div>
      </td>
    </tr>
    <tr>
      <td class="td-text col-md-10"><%= @posting.available_dates.try :first %> to <%= @posting.available_dates.try :last %></td>
    </tr>
    <tr>
      <td colspan="2">
        <div >
          <%= render "reviews/form", :locals => { :review => @review } %> <%= rating_for @posting, "title", disable_after_rate: false %>
        </div>
      </td>
    </tr>
  </tbody>
</table>

app/views/postings/_search_form.html.erb
<div class="input-group">
<%= form_tag postings_path, method: 'get' %>
<%= render partial: 'simple_category_picker' %><%= render 'shared/date_range_picker' %><%= text_field_tag :search_text, params[:search_text], placeholder: 'search text' %>
<%= text_field_tag :city, params[:city], placeholder: 'search city' %><%= submit_tag 'Search' %>
</form>
</div>

app/views/postings/_simple_category_picker.html.erb
<%= select_tag :category_id, options_from_collection_for_select(Category.all, "id", "name", params[:category_id]), include_blank: true %>

app/views/postings/edit.html.erb
<h1 class="heading-text">Edit Posting</h1>

<div class="row">
  <%= render 'form' %>
</div>

app/views/postings/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'postings/search_form' %>
<div class='row'>
  <div class="col-md-7">
    <table class="list-table">
      <tbody class="list-table-body">
        <% @postings.each do |posting| %>
        <tr  id="posting_<%= posting.id %>" class="whitelink">
            <td class="list-table-element">
            <%= link_to(posting.title, action: 'show', id: posting.id) %>
            <td class="list-table-element"><%= posting.category.try :name %></td>
            <td class="list-table-element description-column"><%= posting.description %></td>
            <td class="list-table-element"><%= posting.available_dates %></td>
            <td class="list-table-element"><%= link_to 'Show', posting %>
            <% if current_user && current_user[:id] == posting.user_id %>
              | <%= link_to 'Edit', edit_posting_path(posting) %> |
              <%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @postings %>
    <br>
    <div id="whitelink">
      <%= link_to 'New Posting', new_posting_path, id:"whitelink" %>
    </div>
  </div>
  <div id="map" class="map col-md-4" >
    <!-- <div id="popup" data-original-title="" title=""></div> -->
  </div>
  <div class="popup" data-trigger="hover" data-toggle="popover" data-original-title="" title="" data-placement=""
  ></div>
</div>
<% if @mapAttributes_json %>
<script>
function drawTheThings(){
  if (window.RentMyThing && window.RentMyThing.drawMap) {
    drawMap = window.RentMyThing.drawMap
    mapAttributes = <%= @mapAttributes_json.html_safe %>
    drawMap(mapAttributes)
  } else {
    console.log("Map.js not loaded before trying to draw map")
  }
}
$(document).on ('page:change', drawTheThings);
$(document).ready(drawTheThings);
</script>
<% else %>
   <% logger.debug(" !!!!!!!! No coords for posting(s) so map not drawn !!!!!!!!!") %>
<% end %>

app/views/postings/new.html.erb
<h3>New Posting</h3>
<br>
<%= render 'form' %>

<%#= link_to 'Back', postings_path %>

app/views/postings/show.html.erb
<div class='row'>
  <div class="showpage col-md-6" id='blacklink' >

    <div class="row">
      <%= render 'carousel' %>
    </div>
    <br>
    <div class="row">
      <%= render 'posting_table' %>
    </div>

    <div class="row">
      <div id='reserve'>
        <%= form_tag new_posting_reservation_path(@posting), method: :get %>
          <%= render 'shared/date_range_picker_group' %>
          <%= submit_tag "Reserve", :class => 'btn btn-primary', :role => "button" %>
        </form>
      </div>
    </div>

  </div>

  <div class="col-md-6">
    <div id="cost">
      COST <%= @posting.cost %>
    </div>
    <div id="offerContainer">
      <div id='offeredBy'>
        OFFERED BY
        <% if @posting.user %>
        <div class="col-md-10"><%= link_to  @posting.user.email, @posting.user %></div>
        <% else %>
        <div class="col-md-10"></div>
        <% end %>
      </div>
    </div>

    <div id="map" class="map">
    </div>
    <div class="popup" data-trigger="hover" data-toggle="popover" data-original-title="" title="" data-placement=""></div>
  </div>

  <div class="container col-md-6">

  <div class="row">
    <br><br>
    <div class="btn-group">
      <%= link_to 'Edit', edit_posting_path(@posting), :class => "btn btn-primary", :role => "button" %>
      <%= link_to 'Back', postings_path, :class => "btn btn-primary", :role => "button" %>
    </div>
  </div>

  <div class="row">
    <h3><strong> REVIEWS </strong></h3>
    <table class="table table-bordered">
      <thead>
        <th>Comments</th>
        <th>Created</th>
        <th>Rating</th>
      </thead>
      <tbody>
        <%= render @reviews %>
      </tbody>
    </table>
  </div>
</div>

<% if @mapAttributes_json %>
<script>
  function drawTheThings(){
    if (window.RentMyThing && window.RentMyThing.drawMap) {
      drawMap = window.RentMyThing.drawMap
      mapAttributes = <%= @mapAttributes_json == nil ? nil : @mapAttributes_json.html_safe %>
      drawMap(mapAttributes)
    } else {
      console.log("Map.js not loaded before trying to draw map")
    }
  }
  $(document).on ('page:change', drawTheThings);
  $(document).ready(drawTheThings);
</script>
<% end %>

app/views/postings/splash.html.erb
<div class="search-area text-center page-container-responsive page-container-no-padding">
  <video controls muted autoplay loop id="video-bg">
    <source src="http://ryanclifton.com/Learn%20Bootcamp%202.mp4" type="video/mp4">
      <source src="https://a0.muscache.com/airbnb/static/London-P1-0.webm" type="video/webm">
        Your browser does not support the video tag.
      </video>

    </div>

    <% content_for :afterbody do %>
    <script>
    $( document ).ready(function() {
    $("h2").lettering();

// hack to get animations to run again
$("h2").click(function() {
  var el = $(this),
     newone = el.clone();
  el.before(newone);
  el.remove();
});


var text = $("#jquerybuddy");
numLetters = text.find("span").length;

function randomBlurize() {
text.find("span:nth-child(" + (Math.floor(Math.random()*numLetters)+1) + ")")
  .animate({
    'textShadowBlur': Math.floor(Math.random()*25)+4,
    'textShadowColor': 'rgba(0,100,0,' + (Math.floor(Math.random()*200)+55) + ')'
  });
// Call itself recurssively
setTimeout(randomBlurize, 100);
} // Call once
randomBlurize();
})
</script>
<% end %>

    <div >
      <h2 class="hovertown">Rent. Loan. Discover.</h2>
    </div>
    <br>
    <div class="splashtext">
      <h2>Choose from thousands of local, instant, affordable rentals.</h2>
      <h3>Select a category & city to begin.</h3>
    </div>
    <br>



    <div class="bottom-search-area hide-sm">
      <form action="<%= postings_path %>" id="search_form">
        <div class="location-wrapper">
      <div class="styled-select black rounded">
        <%= select_tag :category_id, options_from_collection_for_select(Category.all, "id", "name", params[:category_id]), include_blank: "Select a Category" %>
      </div><br>
        <input type="text" class="form-inline location input-large input-contrast" autocomplete="off" id="location" name="city" placeholder="City" /><p id="enter_location_error_message" class="bad hide">
        </p></div><br>
        <%= text_field_tag :search_text, params[:search_text], placeholder: 'Item Description' %><br><br>
        <button type="submit" class="search-button form-inline btn btn-primary btn-large" id="submit_location">
          Search
        </button>
      </form>

    </div>
  </div>

</div>