config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins
  resources :reservations
  resources :reviews
  resources :uploads

  devise_for :users
  resources :users
  resources :users do
    resources :postings, :reviews
  end

  root "postings#splash"

  resources :categories do
    resources :postings
  end

  resources :postings do
    resources :reservations
    resources :reviews
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :posting
  belongs_to :user

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include Reservable

  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /reservations
  # GET /reservations.json
  def index
    # logger.debug ("Current user: #{current_user[:id]}  User Id: #{params[:id]}")
    @reservations = Reservation.where("user_id = " + current_user[:id].to_s)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @posting = Posting.find params[:posting_id]
    #parse params[:reservation] and assign to @reservation
    @reservation.when = date_range_from_param params[:reservation]
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    res_params = reservation_params
    res_when = res_params.delete :when
    res_params[:when] = date_range_from_param res_when if res_when
    @reservation = Reservation.new(res_params)
    @reservation.posting_id = params[:posting_id]
    @reservation.user = current_user

    respond_to do |format|
      if @reservation.save
        logger.debug "Reservation: #{@reservation.when.first} to #{@reservation.when.last}"
        logger.debug "Got reservation: #{@reservation.inspect}"
        MailerGenerator.send_reservation_email("id" => @reservation.id)
        format.html { redirect_to @reservation, notice: 'Congratulations on your rental!' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
      @posting = @reservation.posting
      @user = @reservation.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :posting_id, :when)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for([@posting, @reservation]) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= [ @reservation.when.first ]%>
     to
    <%= [ @reservation.when.last ]%>
  </div>

  <%= f.hidden_field :when, value: "#{@reservation.when.begin.strftime '%m-%d-%Y'} - #{@reservation.when.end.strftime '%m-%d-%Y'}" %>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Your Reservations</h3>

<table>
  <thead class="table table-styled table-bordered">
    <tr>
      <th>User</th>
      <th>Posting</th>
      <th>When</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.user.try :email %></td>
        <td><%= reservation.posting.try :title %></td>
        <td><%= reservation.when %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reservations/new.html.erb
<h1>Confirm Reservation</h1>
<br><HR>
<strong>  User requesting reservation: </strong>
<br><br>
<%= current_user.email %>
<br><br>
<strong>  Item to be reserved: </strong>
<br><br>
<%= @posting.title %>
<br><br>
<strong>  Dates Requested: </strong>
<br><br>
<%= render 'form' %>

<div class="btn-group">
  <%= link_to 'Cancel', posting_path(@posting.id), :class => "btn btn-primary", :role => "button" %>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<div id="inlineblock">
<p id="box">
  <strong>User:</strong>
  <%= @reservation.user.try :email %>
</p>

<p id="box">
  <strong>Posting:</strong>
  <%= @reservation.posting.try :title %>
</p>
</div>

<div id="inlineblock">
<p id="box">
  <strong>When:</strong>
  <%= @reservation.when %>
</p>

<p id="box">
  <strong>Cost:</strong>
  <%= @reservation.posting.try :cost %> per day
</p>
</div>

<br><br>

<%= link_to 'My Reservations', reservations_path %>